In [1]:
import cv2
import numpy as np

img = cv2.imread('sample/star.jpg',0)
ret,thresh = cv2.threshold(img,127,255,0)
_, contours,hierarchy = cv2.findContours(thresh, 1, 2)

cnt = contours[0]
M = cv2.moments(cnt)
print M

{'mu02': 0.3333333332557231, 'mu03': 2.384185791015625e-07, 'm11': 1251678.0, 'nu02': 0.08333333331393078, 'm12': 1150292309.0, 'mu21': 1.1106021702289581e-07, 'mu20': 0.3333333332557231, 'nu20': 0.08333333331393078, 'm30': 631643163.0, 'nu21': 1.9632858144234817e-08, 'mu11': 0.0, 'mu12': 5.2852556109428406e-08, 'nu11': 0.0, 'nu12': 9.34310020700483e-09, 'm02': 1689122.3333333333, 'm03': 1552304037.0, 'm00': 2.0, 'm01': 1838.0, 'mu30': 1.1920928955078125e-07, 'nu30': 2.1073424255447017e-08, 'nu03': 4.2146848510894035e-08, 'm10': 1362.0, 'm20': 927522.3333333333, 'm21': 852393024.3333334}


In [2]:
cnt

array([[[680, 919]],

       [[681, 918]],

       [[682, 919]],

       [[681, 920]]])

In [3]:
area = cv2.contourArea(cnt)

In [4]:
area

2.0

In [5]:
perimeter = cv2.arcLength(cnt, True)

In [6]:
perimeter

5.656854152679443

In [7]:
epsilon = 0.1*cv2.arcLength(cnt,True)
approx = cv2.approxPolyDP(cnt,epsilon,True)

#cv2.imshow('image', img)
#cv2.imshow('image1', thresh)
#cv2.imshow('image2', approx)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

In [8]:
approx

array([[[680, 919]],

       [[681, 918]],

       [[682, 919]],

       [[681, 920]]])

In [9]:
hull = cv2.convexHull(cnt)

In [10]:
hull

array([[[682, 919]],

       [[681, 920]],

       [[680, 919]],

       [[681, 918]]])

In [11]:
k = cv2.isContourConvex(cnt)

In [12]:
k

True

In [13]:
x,y,w,h = cv2.boundingRect(cnt)
imgrectan = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
cv2.imshow('image', img)
cv2.imshow('imagerectan', imgrectan)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
rect = cv2.minAreaRect(cnt)
box = cv2.boxPoints(rect)
box = np.int0(box)
im = cv2.drawContours(img,[box],0,(0,0,255),2)

In [15]:
x,y,w,h = cv2.boundingRect(cnt)

In [16]:
aspect_ratio = float(w) / h

In [17]:
aspect_ratio

1.0